<a href="https://colab.research.google.com/github/lsc2159/LinearA_single/blob/main/LinearAlgebra_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A=np.array([1,2,3])
B=np.array([-1,-2,-3])
C=A+B

print(C)

[0 0 0]


In [ ]:
c=np.array([1,2,3], dtype=np.float64)
c
c.dtype
type(c[0])

numpy.float64

In [ ]:
d=np.array([1.1,2.2,3.3,4.9])
d.dtype
e=d.astype(np.int32)
e

array([1, 2, 3, 4], dtype=int32)

In [ ]:
A=np.array([[1,2,3],[4,5,6]])
A
type(A)
A
A.ndim
A.shape

(2, 3)

In [ ]:
A=np.array([[1,2,3],[4,5,6]])
A.size

6

In [ ]:
A=np.array([[1, 2, 3],
            [4, 5, 6]])
A.itemsize

8

In [ ]:
A=np.array([[1,2,3],[4,5,6]])
A.data

In [ ]:
b=np.array([1,2,3,4,5,6])
b.max() #6
b.min()  #1
b.sum()  #21
b.mean() #3.5
b.std() #1.707825127659933

1.707825127659933

In [ ]:
c=np.array([[1,2],[3,4]])
c #array([[1, 2],
      # [3, 4]])
c.sum(axis=0) #array([4, 6])
c.sum(axis=1) #array([3, 7])

array([3, 7])

In [ ]:
import numpy as np
B=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])
print(B)
print(B.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [ ]:
import numpy as np
C=np.arange(24).reshape(2,3,4)
print(C)
print(C.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [ ]:
import numpy as np
A=np.linspace(0,10,10)
print(A)
B=np.linspace(0,100)
print(B)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]


In [ ]:
import numpy as np
A=np.arange(16)
B=A.reshape(4,4)
print(B)
print(B.shape)
print(B.base)
print(B.base is A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
True


In [ ]:
import numpy as np
A=np.arange(16)
B=A.reshape(4,4)
print(B)
print(B.shape)
print(B.base)
print(B.base is A)

B[0]=-1
print(A)
print(B)

C=B.reshape(2,8).copy()
print(C)
print(C.shape)
C[0]=0
print(B)
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
True
[-1 -1 -1 -1  4  5  6  7  8  9 10 11 12 13 14 15]
[[-1 -1 -1 -1]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[-1 -1 -1 -1  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
(2, 8)
[[-1 -1 -1 -1]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  0  0  0  0  0  0  0]
 [ 8  9 10 11 12 13 14 15]]


In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
print(A)
print(A.shape)
B=A.ravel()
print(B)
print(B.shape)
print(B.base)
print(B.base is A)

In [ ]:
import numpy as np
A=np.arange(12)
print(A)
A.resize(3,4)
print(A)

In [ ]:
import numpy as np
A=np.array([1,2,3])
A=A[:,np.newaxis]
print(A.shape)
print(A)
B=np.array([4,5,6])
B=B[np.newaxis,:]
print(B.shape)
print(B)

In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[1,0],[0,1]])
print(A)
print(B)
C=np.vstack((A,B))
print(C)

In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[1,0],[0,1]])
print(A)
print(B)
C=np.hstack((A,B))
print(C)

In [ ]:
import numpy as np
A=np.array([1,2,3])
B=np.array([4,5,6])
C=np.array([7,8,9])
E=np.column_stack((A,B,C))
print(E)

In [ ]:
import numpy as np
A=np.array([[1,2],[3,4]])
B=np.array([[1,0],[0,1]])
print(A)
print(B)
print(np.concatenate((A,B),axis=0))
print(np.concatenate((A,B),axis=1))

In [ ]:
#대입
import numpy as np
A=np.arange(12)
B=A
print(A==B)
print(A is B)
A[0]=100
B[11]=-1
print(A)
print(B)
B.shape=3,4
print(A.shape)

def f(x):
  print(id(x))

a=np.array([1,2])
print(id(a))
print(f(a))

In [ ]:
#얕은복사
import numpy as np
a=np.arange(12)
b=a.view()
print(a)
print(b)
print(b.base is a,a is b)
a[0]=-1
b[11]=100
print(a)
print(b)

a.resize(3,4)
print(a)
print(b)

a[0,2]=10000
print(a)
print(b)

c=a[0]
c[:]=0
print(c)
print(a)
print(b)

In [ ]:
#깊은복사
import numpy as np
a=np.arange(12)
b=a.copy()
print(a==b)
print(a is b)
print(b.base is a)
a[0]=-1
b[11]=10000
print(a)
print(b)

In [ ]:
import numpy as np
A=np.array([[7,2],[-7,5]])
b=np.array([-5,12])
invA=np.linalg.inv(A)
x=np.dot(invA,b)
print(x)

A=np.array([[7,2],[-7,5]])
b=np.array([-5,12])
x=np.linalg.solve(A,b)
print(x)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
A=np.array([[7,2],[-7,5]])
b=np.array([-5,12])
x=np.linalg.solve(A,b)

x1,y1=x
print(x1,y1)
fig=plt.figure()
ax=fig.add_subplot(1,1,1)
a1=A[:,0]
b1=A[:,1]
c1=-b

for c1, c2,c3 in zip(A[:,0],A[:,1],b):
  x=np.linspace(-7,7,100)
  y=(c3-c1*x)/c2
  ax.plot(x,y,color="black")
ax.plot(x1,y1,'ro')
ax.axis([-7,7,-7,7])
ax.set_xticks(range(-7,7))
ax.set_yticks(range(-7,7))
ax.grid()
ax.set_axisbelow(True)
ax.set_aspect('auto',adjustable='box')
ax.spines['left'].set_position('zero')
ax.spines['bottom'].set_position('zero')
ax.spines['right'].set_color('none')
ax.spines['bottom'].set_color('none')
plt.show()

In [ ]:
import cv2
import numpy as np
from google.colab.patches import cv2_imshow
img=cv2.imread('/content/gdrive/My Drive/Colab Notebooks/Kakao1.jpg')
height,width=img.shape[:2]
M=np.array([[1,0,100],[0,1,200],[0,0,1]],dtype=float)
dst=np.zeros(img.shape,dtype=np.uint8)
for y in range(height-1):
  for x in range(width-1):
    p=np.array([x,y,1])
    p_=np.dot(M,p)
    x_,y_=p_[:2]
    x_=int(x_)
    y_=int(y_)
    if x_>0 and x_<width and y_>0 and y_<height:
      dst[y_,x_]=img[y,x]
result=cv2.hconcat([img,dst])

cv2_imshow(result)
cv2.waitKey(0)

In [ ]:
import cv2
import numpy as np
from google.colab.patches import cv2_imshow
img=cv2.imread('/content/gdrive/My Drive/Colab Notebooks/Kakao1.jpg')
height,width=img.shape[:2]

angle=45
radian=angle*np.pi/180
c=np.cos(radian)
s=np.sin(radian)

rotation_matrix=np.array([[c,s,0],[-s,c,0],[0,0,1]],dtype=float)
dst=np.zeros(img.shape,dtype=np.unit8)
for y in range(height-1):
  for x in range(width-1):
    new_p=np.array([x,y,1])
    inv_rotation_matrix=np.linalg.inv(rotation_matrix)
    old_p=np.dot(inv_rotation_matrix,new_p)
    x_,y_=old_p[:2]
    x_=int(x_)
    y_=int(y_)

    if x_>0 and x_<width and y_>0 and y_<height:
      dst[y,x]:img[_y,_x]
  result=cv2.hconcat([img,dst])
  cv2_imshow(result)
  cv2.waitkey(0)

In [ ]:
import cv2
import numpy as np
from google.colab.patches import cv2_imshow
img=cv2.imread('/content/drive/MyDrive/Colab Notebooks/KAKAO1.jpg')
height,width=img.shape[:2]

angle=45
radian=angle*np.pi/180
c=np.cos(radian)
s=np.sin(radian)
center_x=width/2
center_y=height/2

rotation_matrix=np.array([[c,s,(1-c)*center_x-s*center_y],[-s,c,s*center_x+(1-c)*center_y],[0,0,1]])
dst=np.zeros(img.shape,dtype=np.unit8)
for y in range(height-1):
  for x in range(width-1):
    new_p=np.array([x,y,1])
    inv_rotation_matrix=np.linalg.inv(rotation_matrix)
    old_p=np.dot(inv_rotation_matrix,new_p)
    x_,y_=old_p[:2]
    x_=int(x_)
    y_=int(y_)

    if x_>0 and x_<width and y_>0 and y_<height:
      dst[y,x]:img[_y,_x]
  result=cv2.hconcat([img,dst])
  cv2_imshow(result)
  cv2.waitkey(0)

In [ ]:
import numpy as np
A=np.array([10])
B=np.array([[1,2],[3,4]])
C=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.linalg.det(B))
print(np.linalg.det(C))

-2.0000000000000004
0.0


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
points=np.array([[1,1],[1,2],[2,2],[2,1]])
A=np.array([[2,0],[0,2]])
fig=plt.figure()
ax=fig.add_subplot(1,1,1)
print(np.linalg.det(A))

ax.add_patch(patches.Polygon(points,fill=False,color='blue',zorder=1))
ax.add_patch(patches.Polygon(np.dot(points,A),fill=False,color='blue',zorder=1))
ax.text(1.4,1.4,'A',size=15)
ax.text(2.9,2.9,'B',size=15)
ax.set_xticks(range(-1,6))
ax.set_yticks(range(-1,6))
ax.grid()
ax.set_axisbelow(True)
ax.set_aspect('auto',adjustable='box')
ax.spines['left'].set_position('zero')
ax.spines['bottom'].set_position('zero')
ax.spines['right'].set_color('none')
ax.spines['top'].set_color('none')
plt.show()

In [ ]:
import numpy as np
A=np.array([[3,2],[4,1]])
print("A")
print(A)
print()
eigenvalue,eigenvector=np.linalg.eig(A)
print("Eigen-Value")
print(eigenvalue)
print("Eigen-Vector")
print(eigenvector)
print()

eigenvector1=eigenvector[:,0]
eigenvector2=eigenvector[:,1]
eigenvalue1=eigenvalue[0]
eigenvalue2=eigenvalue[1]

print("lambda*eigenvector==A*eigenvector")
print(eigenvalue1*eigenvector1,np.dot(A,eigenvector1))
print(eigenvalue2*eigenvector2,np.dot(A,eigenvector2))

In [ ]:
import cv2
import numpy as np
from google.colab.patches import cv2_imshow
img=cv2.imread('/content/drive/MyDrive/Colab Notebooks/KAKAO1.jpg')
height,width=img.shape[:2]
scale_factor=0.5
scaling_matrix=np.array([[scale_factor,0,0],[0,scale_factor,0],[0,0,1]])
dst=np.zeros((height,width,img.shape[2]),dtype=np.uint8)
for y in range(height):
  for x in range(width):
    new_p=np.array([x,y,1])
    inv_scaling_matrix=np.linalg.inv(scaling_matrix)
    old_p=np.dot(inv_scaling_matrix,new_p)
    x_ ,y_=old_p[:2]
    x_=int(x_)
    y_=int(y_)
    if x_>0 and x_<width and y_ >0 and y_<height:
      dst.itemset((y,x,0),img.item(y_,x_,0))
      dst.itemset((y,x,1),img.item(y_,x_,1))
      dst.itemset((y,x,2),img.item(y_,x_,2))

result=cv2.hconcat([img,dst])
cv2_imshow(result)
cv2.waitkey(0)

In [ ]:
import cv2
import numpy as np
img=cv2.imread('/content/drive/MyDrive/Colab Notebooks/KAKAO1.jpg')
height, width=img.shape[:2]
dst=cv2.resize(img,(int(width*1.5),int(height*1.5)))

cv2_imshow(dst)
cv2.waitkey(0)

In [ ]:
import cv2
import numpy as np
img=cv2.imread('/content/drive/MyDrive/Colab Notebooks/KAKAO1.jpg')
height, width=img.shape[:2]
scale_factor=0.5
scaling_matrix=np.array([[scale_factor,0,0],[0,scale_factor,0],[0,0,1]])
translation_matrix=np.array([[1,0,width/4],[0,1,height/4],[0,0,1]])
angle=45
radian=angle*np.angle
c=np.cos(radian)
s=np.sin(radian)
center_x=width/2
center_y=height/2
rotation_matrix=np.array([[c,s,(1-c)*center_x-s*center_y],[-s,c,s*center_x+(1-c)*center_y],[0,0,1]])

T=np.eye(3)
T=np.dot(scaling_matrix,T)
T=np.dot(translation_matrix,T)
T=np.dot(rotation_matrix,T)
dst=np.zeros((height,width,img.shape[2]),dtype=np.uint8)
for y in range(height):
  for x in range(width):
    new_p=np.array([x,y,1])
    inv_scaling_matrix=np.linalg.inv(T)
    old_p=np.dot(inv_scaling_matrix,new_p)
    x_,y_=old_p[:2]
    x_=int(x_)
    y_=int(y_)
    if x_>0 and x><width and y_>0 and y_<height:
      dst.itemset((y,x,0),img.item(y_,x_,0))
      dst.itemset((y,x,1),img.item(y_,x_,1))
      dst.itemset((y,x,2),img.item(y_,x_,2))
cv2.imshow("result",dst)
cv2.waitKey(0)